"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 11:16:24.507704
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector is installed by the database bootstrap (superuser); this is a no-op then.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_budgets',
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('tokens', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'day')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('workspace_id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('insufficient', sa.Boolean(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_answers_workspace_id'), 'answers', ['workspace_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.String(length=400), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'chunk_key'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_workspace_id'), 'chunks', ['workspace_id'], unique=False)
    op.create_table('claim_rejections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('rejection_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'rejection_key')
    )
    op.create_index(op.f('ix_claim_rejections_workspace_id'), 'claim_rejections', ['workspace_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_account', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'provider')
    )
    op.create_index(op.f('ix_connections_workspace_id'), 'connections', ['workspace_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('exclusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=15), nullable=False),
    sa.Column('key', sa.String(length=400), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'scope', 'key')
    )
    op.create_index(op.f('ix_exclusions_workspace_id'), 'exclusions', ['workspace_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_table('next_step_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('step_key', sa.String(length=200), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'step_key')
    )
    op.create_index(op.f('ix_next_step_states_workspace_id'), 'next_step_states', ['workspace_id'], unique=False)
    op.create_table('oauth_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('browser_hash', sa.String(length=64), nullable=False),
    sa.Column('cookie_name', sa.String(length=64), nullable=False),
    sa.Column('verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('name_source', sa.String(length=20), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_people_workspace_id'), 'people', ['workspace_id'], unique=False)
    op.create_table('provider_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_workspace_id'), 'provider_usage', ['workspace_id'], unique=False)
    op.create_table('self_profiles',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_account', sa.String(length=255), nullable=False),
    sa.Column('provider_object_id', sa.String(length=400), nullable=False),
    sa.Column('conversation_id', sa.String(length=400), nullable=True),
    sa.Column('conversation_title', sa.String(length=300), nullable=True),
    sa.Column('version', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=320), nullable=True),
    sa.Column('author_label', sa.String(length=200), nullable=True),
    sa.Column('from_me', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_truncated', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'provider_account', 'provider_object_id')
    )
    op.create_index('ix_sources_conversation', 'sources', ['workspace_id', 'provider', 'conversation_id'], unique=False)
    op.create_index('ix_sources_time', 'sources', ['workspace_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_table('whatsapp_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('desired', sa.String(length=20), nullable=False),
    sa.Column('observed', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_enc', sa.Text(), nullable=False),
    sa.Column('account_wid', sa.String(length=100), nullable=True),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('chunk_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'chunk_id'], ['chunks.workspace_id', 'chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['sources.workspace_id', 'sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'chunk_id', 'source_id')
    )
    op.create_index(op.f('ix_chunk_sources_chunk_id'), 'chunk_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_sources_source_id'), 'chunk_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_chunk_sources_workspace_id'), 'chunk_sources', ['workspace_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('attribute', sa.String(length=40), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('basis', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('origin', sa.String(length=15), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'claim_key'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_claims_person_id'), 'claims', ['person_id'], unique=False)
    op.create_index(op.f('ix_claims_workspace_id'), 'claims', ['workspace_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'event_id'], ['events.workspace_id', 'events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_drafts_event_id'), 'drafts', ['event_id'], unique=False)
    op.create_index(op.f('ix_drafts_workspace_id'), 'drafts', ['workspace_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'chunk_id'], ['chunks.workspace_id', 'chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'chunk_id', 'model')
    )
    op.create_index(op.f('ix_embeddings_workspace_id'), 'embeddings', ['workspace_id'], unique=False)
    op.create_table('event_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'event_id'], ['events.workspace_id', 'events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_candidates_event_id'), 'event_candidates', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_candidates_workspace_id'), 'event_candidates', ['workspace_id'], unique=False)
    op.create_table('event_people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suggested_status', sa.String(length=20), nullable=True),
    sa.Column('suggested_source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id', 'event_id'], ['events.workspace_id', 'events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'event_id', 'person_id'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_event_people_event_id'), 'event_people', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_people_workspace_id'), 'event_people', ['workspace_id'], unique=False)
    op.create_table('person_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('linked_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'kind', 'value')
    )
    op.create_index(op.f('ix_person_identifiers_person_id'), 'person_identifiers', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_identifiers_workspace_id'), 'person_identifiers', ['workspace_id'], unique=False)
    op.create_table('relationship_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_notes_person_id'), 'relationship_notes', ['person_id'], unique=False)
    op.create_index(op.f('ix_relationship_notes_workspace_id'), 'relationship_notes', ['workspace_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_workspace_id'), 'sessions', ['workspace_id'], unique=False)
    op.create_table('source_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'person_id'], ['people.workspace_id', 'people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['sources.workspace_id', 'sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_id', 'identifier', 'role')
    )
    op.create_index(op.f('ix_source_participants_person_id'), 'source_participants', ['person_id'], unique=False)
    op.create_index(op.f('ix_source_participants_source_id'), 'source_participants', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_participants_workspace_id'), 'source_participants', ['workspace_id'], unique=False)
    op.create_table('sync_streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id', 'connection_id'], ['connections.workspace_id', 'connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connection_id', 'stream'),
    sa.UniqueConstraint('workspace_id', 'id')
    )
    op.create_index(op.f('ix_sync_streams_workspace_id'), 'sync_streams', ['workspace_id'], unique=False)
    op.create_table('answer_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'answer_id'], ['answers.workspace_id', 'answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'draft_id'], ['drafts.workspace_id', 'drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['sources.workspace_id', 'sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_sources_answer_id'), 'answer_sources', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_sources_draft_id'), 'answer_sources', ['draft_id'], unique=False)
    op.create_index(op.f('ix_answer_sources_source_id'), 'answer_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_answer_sources_workspace_id'), 'answer_sources', ['workspace_id'], unique=False)
    op.create_table('claim_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'claim_id'], ['claims.workspace_id', 'claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['sources.workspace_id', 'sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'claim_id', 'source_id')
    )
    op.create_index(op.f('ix_claim_sources_claim_id'), 'claim_sources', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_sources_source_id'), 'claim_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_claim_sources_workspace_id'), 'claim_sources', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_sources_workspace_id'), table_name='claim_sources')
    op.drop_index(op.f('ix_claim_sources_source_id'), table_name='claim_sources')
    op.drop_index(op.f('ix_claim_sources_claim_id'), table_name='claim_sources')
    op.drop_table('claim_sources')
    op.drop_index(op.f('ix_answer_sources_workspace_id'), table_name='answer_sources')
    op.drop_index(op.f('ix_answer_sources_source_id'), table_name='answer_sources')
    op.drop_index(op.f('ix_answer_sources_draft_id'), table_name='answer_sources')
    op.drop_index(op.f('ix_answer_sources_answer_id'), table_name='answer_sources')
    op.drop_table('answer_sources')
    op.drop_index(op.f('ix_sync_streams_workspace_id'), table_name='sync_streams')
    op.drop_table('sync_streams')
    op.drop_index(op.f('ix_source_participants_workspace_id'), table_name='source_participants')
    op.drop_index(op.f('ix_source_participants_source_id'), table_name='source_participants')
    op.drop_index(op.f('ix_source_participants_person_id'), table_name='source_participants')
    op.drop_table('source_participants')
    op.drop_index(op.f('ix_sessions_workspace_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_relationship_notes_workspace_id'), table_name='relationship_notes')
    op.drop_index(op.f('ix_relationship_notes_person_id'), table_name='relationship_notes')
    op.drop_table('relationship_notes')
    op.drop_index(op.f('ix_person_identifiers_workspace_id'), table_name='person_identifiers')
    op.drop_index(op.f('ix_person_identifiers_person_id'), table_name='person_identifiers')
    op.drop_table('person_identifiers')
    op.drop_index(op.f('ix_event_people_workspace_id'), table_name='event_people')
    op.drop_index(op.f('ix_event_people_event_id'), table_name='event_people')
    op.drop_table('event_people')
    op.drop_index(op.f('ix_event_candidates_workspace_id'), table_name='event_candidates')
    op.drop_index(op.f('ix_event_candidates_event_id'), table_name='event_candidates')
    op.drop_table('event_candidates')
    op.drop_index(op.f('ix_embeddings_workspace_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_drafts_workspace_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_event_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_claims_workspace_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_person_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_chunk_sources_workspace_id'), table_name='chunk_sources')
    op.drop_index(op.f('ix_chunk_sources_source_id'), table_name='chunk_sources')
    op.drop_index(op.f('ix_chunk_sources_chunk_id'), table_name='chunk_sources')
    op.drop_table('chunk_sources')
    op.drop_table('whatsapp_connectors')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_index('ix_sources_time', table_name='sources')
    op.drop_index('ix_sources_conversation', table_name='sources')
    op.drop_table('sources')
    op.drop_table('self_profiles')
    op.drop_index(op.f('ix_provider_usage_workspace_id'), table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index(op.f('ix_people_workspace_id'), table_name='people')
    op.drop_table('people')
    op.drop_table('oauth_flows')
    op.drop_index(op.f('ix_next_step_states_workspace_id'), table_name='next_step_states')
    op.drop_table('next_step_states')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_exclusions_workspace_id'), table_name='exclusions')
    op.drop_table('exclusions')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_connections_workspace_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_claim_rejections_workspace_id'), table_name='claim_rejections')
    op.drop_table('claim_rejections')
    op.drop_index(op.f('ix_chunks_workspace_id'), table_name='chunks')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_answers_workspace_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_table('accounts')
    op.drop_table('workspaces')
    op.drop_table('usage_budgets')
    # ### end Alembic commands ###
